### ISSUE TITLE
win7 Goland 运行卡住

### ISSUE THREAD

**Issue by Gui1105** [helloworlde/SoarPlugin#9]
![tim 20181214110859](https://user-images.githubusercontent.com/29769388/49980967-b3b29980-ff90-11e8-9169-b0e00e6bcb2d.png)

**Comment by helloworlde** [comment]
SQL 和错误日志发一下，SOAR 执行分析的时候会从生产库拷贝数据到测试库进行分析，如果涉及的表很多会比较慢；先确认一下是一直卡死了还是响应慢

**Comment by ghost** [comment]
我的也是，我用的是IDEA2018.1版本，分析一条最简单的select语句，一直卡在那没反应

**Comment by helloworlde** [comment]
@FJarvan 在 SOAR 安装路径下有 soar.log ，贴一下错误信息
